n1 = input('Digite algo: ')
print('O tipo primitivo desse valor é: ', type(n1))
print('É um número? ', n1.isnumeric())
print('É alfanumérico? ', n1.isalnum())
print('É alfabético? ', n1.isalpha())
print('É um decimal? ', n1.isdecimal())
print('Está em minuscula? ', n1.islower())
print('Está em maiuscula? ', n1.isupper())
print('Está capitalizada? ', n1.istitle())
print('Só possui espaços? ', n1.isspace())
print('É "printável"? ', n1.isprintable())
